### ISSUE TITLE
tensorflow/resnet50.py 无法在CPU下训练

### ISSUE THREAD

**Issue by kolinwei** [dzhwinter/benchmark#43]
可能是在文件 tensorflow/resnet50.py
 474   if tf.test.is_built_with_cuda():

如果是gpu版本的tensorflow的话，始终返回true。

**Comment by chengduoZH** [comment]
这里有说明如何在CPU下训练 https://github.com/dzhwinter/benchmark/blob/master/HowToDoBenchmark.md#经典模型在fluid0110-和tensorflow上的对比

**Comment by kolinwei** [comment]
照着说明，仍然是无法在CPU训练的，我意思是只要安装了GPU版本的tf。
 if tf.test.is_built_with_cuda() 一定是会返回True的。

**Comment by kolinwei** [comment]
sorry，刚看到代码更新，现在应该是可以了
