### ISSUE TITLE
fluid/vggl6 的pass_acc计算方式不对

### ISSUE THREAD

**Issue by kolinwei** [dzhwinter/benchmark#48]
代码中在模型训练之前clone出了inference_program，此时的main_program中各个op的参数还未训练出来，后续直接使用  inference_program进行测试集的正确率计算时，inference_program中的模型参数还是初始化时候的。自然得出的准确率是不准确的。

**Comment by chengduoZH** [comment]
> 代码中在模型训练之前clone出了inference_program，此时的main_program中各个op的参数还未训练出来，后续直接使用 inference_program进行测试集的正确率计算时，inference_program中的模型参数还是初始化时候的...

首先要说一点，在这段代码里`inference_program `和`fluid.default_main_program()`共用一个`startup_program`
https://github.com/dzhwinter/benchmark/blob/60b9f421ab454038d7670ea9887d64bdd8600c5a/fluid/vgg16.py#L93-L98

至于为什么要交`inference_program`，我不是很清楚，感觉不是非常必要 @kuke

**Comment by kuke** [comment]
@kolinwei inference_program中的模型参数会共享main_program中的参数。如果真如你所说，inference_program的参数还是初始化时的参数，你会看到训练过程中test accuracy始终不会发生变化，但事实并非如此。
